dist: trusty
language: bash


services:
  - docker

before_install:
  - sudo mkdir /opt/devoku
  - curl -L https://api.github.com/repos/adaptivdesign/devoku/tarball | sudo tar xz -C /opt/devoku
  - export PATH=$PATH:/opt/devoku/bin/

before_script:
  - devoku service postgres start
  - devoku env new
  - devoku build
  - devoku pg createdb

script:
  - devoku run odooku preload --demo-data
